### ISSUE TITLE
First completed configuration wins, not the first started configuration

### ISSUE THREAD

**Issue by missytake** [r10s/w30-poll#1]
We just had a bit of an annoying situation:

- alice sent a poll
- alice started to configure it
- bob started the configure it as well
- bob finished configuration (it was a troll question, because bob is a troll)
- alice finished configuration, only to see that she could only choose between bob's options, not hers

I assume that when you send the .xdc file, you want to configure it directly. So it's reasonable to expect that whoever started configuring it first, knows what they are doing and isn't trolling.

**Comment by r10s** [comment]
> I assume that when you send the .xdc file, you want to configure it directly.

yip, this is also possible meanwhile, you can configure it in draft mode without anyone disturbing you :) once sent out, configuration is no longer possible, and everyone starts voting.

without using draft mode, the behavior is expected, maybe the app could do differently, but that seems out of scope and not really needed, it is still a demo only :)  therefore closing this issue.
